name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: env
      run: echo $GIT_COMMIT
      env:
        GIT_COMMIT: $GITHUB_SHA
